
@baseUrl = http://localhost:3000

# RECADOS:
###

GET {{baseUrl}}/messages/

###

GET {{baseUrl}}/messages/1

###

POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "message": "Hello, this is a new message!",
  "newKey": "93248234"
}

###

PATCH {{baseUrl}}/messages/1/
Content-Type: application/json

{
  "message": "Hello, this is a new message!"
}

###

DELETE {{baseUrl}}/messages/1/
Content-Type: application/json

{
  "message": "This route deletes a message"
}