
@baseUrl = http://localhost:3000

# RECADOS:
### Get All Messages

GET {{baseUrl}}/messages/
?limit=100
&offset=10

### Get Message by ID

GET {{baseUrl}}/messages/2

### Create a New Message

POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "text": "New message created via REST client",
  "from": "Erica",
  "to": "Johnny"
}

### Update a Message

PATCH {{baseUrl}}/messages/1/
Content-Type: application/json

{
  "text": "UPDATED message text via REST client"
}

### Delete a Message

DELETE {{baseUrl}}/messages/1/
Content-Type: application/json

{
  "message": "This route deletes a message"
}